general:
  seed: 1
  wandb_disabled: "false"
  # wandb_run_id: 
  freeze_encoder: False
  resume_training: True
  load_encoder: False
  ckpt_path: "your checkpoint"


data:
  replace_processed: False
  sax_slice_num: 6 # 6 for 3D, 1 for 2D
  image_size: [128, 128]
  train_num_per_epoch: 1000
  num_train: 6000
  num_val: 100
  num_test: 100
  num_workers: 4
  batch_size: 1
  dataset_cls: Cardiac3DplusTAllAX
  load_seg: True


module:
  task_idx: 2 # reconstrucion: 0, regression: 1, segmentation: 2
  module_idx: 0 # SegMAE: 0
  
  seg_hparams:
    enc_embed_dim: 1025
    enc_depth: 6
    enc_num_heads: 5
    feature_size: 16
    dec_embed_dim: 1152
    spatial_dims: 3
    upsample_kernel_sizes: [[1, 2, 2], [2, 2, 2], [5, 2, 2]]

  training_params:
    lr: 0.00005
    patch_size: [25, 8, 8]
    loss_types: ["dice"] # [mse]
    loss_weights: [1.0]
    train_log_rate: 1
    val_log_rate: 2


trainer:
  max_epochs: 300
  check_val_every_n_epoch: 5
